server:
  port: 8080
spring:
  application:
    name: eureka-server
eureka:
  client:
    #注册中心的地址
    service-url:
      defaultZone: http://localhost:8080/eureka
    #当前的微服务是否可以调用其他的微服务，默认为true
    fetch-registry: false
    #当前的微服务是否注册到eureka上，默认为true
    register-with-eureka: false